INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (1, 'REGISTRADO', 'FORMULACION', 'Proyecto registrado por el estudiante, pendiente de revisión', 1);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (2, 'EN_REVISION_FORMATO', 'FORMULACION', 'En revisión de formato y requisitos mínimos', 2);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (3, 'CON_CORRECCIONES_FORMATO', 'FORMULACION', 'Devuelto con correcciones de formato al estudiante', 3);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (4, 'EN_REVISION_CONTENIDO', 'EVALUACION', 'En evaluación de contenido por evaluadores', 4);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (5, 'CON_CORRECCIONES_CONTENIDO', 'EVALUACION', 'Devuelto con observaciones de contenido', 5);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (6, 'EN_REVISION_COMITE', 'EVALUACION', 'En revisión por el Comité Curricular', 6);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (7, 'CON_OBSERVACIONES_COMITE', 'EVALUACION', 'Devuelto con observaciones del comité', 7);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (8, 'APROBADO_INICIO', 'APROBACION', 'Aprobado para iniciar desarrollo del proyecto', 8);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (9, 'EN_DESARROLLO', 'EJECUCION', 'Proyecto en etapa de desarrollo y ejecución', 9);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (10, 'PRORROGA_SOLICITADA', 'EJECUCION', 'Solicitud de prórroga en evaluación', 10);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (11, 'INFORME_PARCIAL_PRESENTADO', 'EJECUCION', 'Informe parcial de avance presentado', 11);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (12, 'INFORME_FINAL_PRESENTADO', 'EJECUCION', 'Informe final de resultados presentado', 12);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (13, 'EN_REVISION_FINAL', 'CIERRE', 'En revisión de documentación final', 13);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (14, 'SUSTENTACION_PROGRAMADA', 'CIERRE', 'Fecha de sustentación asignada', 14);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (15, 'EN_SUSTENTACION', 'CIERRE', 'Proyecto en proceso de sustentación', 15);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (16, 'CERRADO', 'CIERRE', 'Proyecto cerrado, pendiente de calificación final', 16);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (17, 'FINALIZADO', 'FINALIZACION', 'Proyecto finalizado con calificación registrada', 17);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (18, 'ARCHIVADO', 'FINALIZACION', 'Proyecto archivado históricamente', 18);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (19, 'CANCELADO', 'FINALIZACION', 'Proyecto cancelado por el estudiante', 19);
INSERT INTO public.estados_proyecto (id, estado, fase, descripcion, orden) VALUES (20, 'RECHAZADO', 'FINALIZACION', 'Proyecto rechazado por el comité', 20);
