INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('111', '855', 'Ingeniería Civil', 1);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('112', '857', 'Ingeniería Mecánica', 1);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('115', '856', 'Ingeniería de Sistemas', 1);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('116', '3521', 'Ingeniería Electrónica', 1);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('118', '4083', 'Ingeniería de Minas', 1);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('119', '4995', 'Ingeniería Electromecánica', 1);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('120', '51769', 'Ingeniería Industrial', 1);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('210', '13980', 'Administración de Empresas', 2);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('211', '104072', 'Contaduría Pública', 2);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('212', '53635', 'Comercio Internacional', 2);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('610', '4084', 'Ingeniería Ambiental', 3);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('611', '104181', 'Ingeniería Agroindustrial', 3);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('612', '52128', 'Ingeniería Agronómica', 3);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('613', '107494', 'Zootecnia', 3);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('614', '3617', 'Ingeniería Biotecnológica', 3);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('510', '852', 'Enfermería', 4);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('511', '109048', 'Medicina', 4);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('310', '90901', 'Derecho', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('311', '109046', 'Comunicación Social', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('410', '109044', 'Licenciatura en Matemáticas', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('411', '109045', 'Licenciatura en Informática (Distancia)', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('412', '108514', 'Licenciatura en Educación Comunitaria (Distancia)', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('420', '109051', 'Licenciatura en Educación Infantil', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('421', '109052', 'Licenciatura en Educación Física', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('422', '109053', 'Licenciatura en Lengua Castellana', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('423', '109054', 'Licenciatura en Ciencias Naturales', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('424', '109055', 'Licenciatura en Educación Artística', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('425', '109056', 'Licenciatura en Básica Primaria', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('430', '109057', 'Licenciatura en Filosofía', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('431', '109058', 'Licenciatura en Inglés', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('432', '109059', 'Licenciatura en Ciencias Sociales', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('433', '109060', 'Licenciatura en Educación Religiosa', 5);
INSERT INTO public.programas (codigo, snies, nombre, facultad_id) VALUES ('434', '109061', 'Licenciatura en Educación Especial', 5);
